name: Hellgram macOS

on:
  workflow_dispatch:
  push:
    branches: [hellgram-mac]

concurrency:
  group: hellgram-mac-${{ github.ref }}
  cancel-in-progress: true

jobs:
  macos:
    name: Hellgram macOS (arm64)
    runs-on: macos-latest
    env:
      UPLOAD_ARTIFACT: "true"
      ONLY_CACHE: "false"
      PREPARE_PATH: "Telegram/build/prepare/prepare.py"
    steps:
      - name: Get repository name.
        run: echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV

      - name: Clone.
        uses: actions/checkout@v4
        with:
          submodules: recursive
          path: ${{ env.REPO_NAME }}

      - name: First set up.
        run: |
          sudo chown -R `whoami`:admin /usr/local/share
          brew update
          brew install automake libtool meson nasm ninja pkg-config
          sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
          sudo sed -i '' '/CMAKE_${lang}_FLAGS_DEBUG_INIT/s/ -g//' /opt/homebrew/share/cmake/Modules/Compiler/GNU.cmake
          xcodebuild -downloadPlatform macOS
          # silence xcodebuild warnings
          mkdir -p Files/Library || true

      - name: Ccache.
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ runner.OS }}-hellgram-ccache
          max-size: 5G

      - name: Libraries cache.
        uses: actions/cache@v4
        with:
          path: |
            Libraries
            ThirdParty
          key: ${{ runner.OS }}-libs-${{ hashFiles(format('{0}/{1}', env.REPO_NAME, env.PREPARE_PATH)) }}
          restore-keys: ${{ runner.OS }}-libs-

      - name: Libraries.
        run: |
          ./$REPO_NAME/Telegram/build/prepare/mac.sh silent

      - name: Free up disk space.
        run: find Libraries '(' '(' ! '(' -name '*.a' -o -name '*.h' -o -name '*.hpp' -o -name '*.inc' -o -name '*.cmake' -o -name '*.pc' -o -path '*/include/*' -o -path '*/objects-*' -o -path '*/cache_keys/*' -o -path '*/patches/*' -o -perm +111 ')' -type f ')' -o -empty ')' -delete

      - name: Build Hellgram.
        if: env.ONLY_CACHE == 'false'
        run: |
          cd $REPO_NAME/Telegram
          ./configure.sh \
          -D CMAKE_CONFIGURATION_TYPES=Release \
          -D CMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_ALLOWED=NO \
          -D TDESKTOP_API_ID=38159064 \
          -D TDESKTOP_API_HASH=d0372642fc663849324f887acf9a64c5 \
          -D DESKTOP_APP_DISABLE_AUTOUPDATE=ON \
          -D DESKTOP_APP_DISABLE_CRASH_REPORTS=ON

          cmake --build ../out --config Release --parallel

      - name: Ad-hoc sign.
        run: |
          cd $REPO_NAME/out/Release
          codesign --force --deep --sign - Telegram.app || true

      - name: Move artifact.
        run: |
          cd $REPO_NAME/out/Release
          mkdir artifact
          mv Telegram.app artifact/Hellgram.app
          cd artifact
          zip -qry Hellgram-mac-arm64.zip Hellgram.app

      - name: Upload artifact.
        uses: actions/upload-artifact@v4
        with:
          name: Hellgram-mac-arm64
          path: ${{ env.REPO_NAME }}/out/Release/artifact/Hellgram-mac-arm64.zip
          if-no-files-found: error
          retention-days: 30
